version: "3"

services:

   app:
      container_name: app
      build: .
      # Mount source code and downloaded npm modules for
      # easy and fast development
      volumes:
        - ./app/:/code/app/
      # Only bind to localhost
      # Change to 0.0.0.0 to bind to all IPs
      ports:
        - "127.0.0.1:3000:3000"
